### ISSUE TITLE
Provisioning plugin returns 200 for creation of mappings

### ISSUE THREAD

**Issue by astefanova** [cloudfoundry-incubator/cf-abacus-broker#32]
Currently the provisioning plugin returns `200 OK` for successful POST requests to:

* [metering mappings](https://github.com/cloudfoundry-incubator/cf-abacus-broker/blob/d733442530b680c7a4d96cb22043ed258e454ba9/lib/plugins/provisioning/src/index.js#L201)
* [rating mappings](https://github.com/cloudfoundry-incubator/cf-abacus-broker/blob/d733442530b680c7a4d96cb22043ed258e454ba9/lib/plugins/provisioning/src/index.js#L216)
* [pricing mappings](https://github.com/cloudfoundry-incubator/cf-abacus-broker/blob/d733442530b680c7a4d96cb22043ed258e454ba9/lib/plugins/provisioning/src/index.js#L231)

It should return `201 CREATED`.

After this issue is fixed [broker](https://github.com/cloudfoundry-incubator/cf-abacus-broker/blob/d733442530b680c7a4d96cb22043ed258e454ba9/lib/cf/broker/src/routes/create-service.js#L64) and corresponding test should be reworked to no longer expect `200 OK`.

**Comment by hsiliev** [comment]
Returning 201 now
