### ISSUE TITLE
cfpack does not package dependencies correctly

### ISSUE THREAD

**Issue by georgi-lozev** [cloudfoundry-incubator/cf-abacus-broker#74]
When you execute the `npm run cfpack` command inside one of the extension plugins., for example [provisioning](https://github.com/cloudfoundry-incubator/cf-abacus-broker/blob/9371328b5e36432ccd26c5adfc55647862dbbb8b/lib/plugins/provisioning/package.json#L42), the result package.json is incorrect and you're not able to `cf push` with it.

**Comment by georgi-lozev** [comment]
In fact, this was a misconfiguration from my side. 
Assuming you're in the root of the repo.
```bash
export ADDITIONAL_PACK_DIR="abacus/lib"
export ABACUS_ROOT=`pwd`
```

Then go to the specific module and run `npm install` and `npm run cfpack`.

**Comment by hsiliev** [comment]
Fixed https://github.com/cloudfoundry-incubator/cf-abacus-broker/wiki/Deploying
