### ISSUE TITLE
Use separate module for default provisioning plans and mappings

### ISSUE THREAD

**Issue by georgi-lozev** [cloudfoundry-incubator/cf-abacus-broker#78]
As a result of https://github.com/cloudfoundry-incubator/cf-abacus-broker/pull/76 @hsiliev has proposed to use a separate module to store only plans and mappings.

This will eliminate the dependency between abacus-ext-provisioning and abacus-provisioning and will not duplicate the default plans/mappings in both repositories.

**Comment by hsiliev** [comment]
We merged provisioning back in Abacus, so this problem is not relevant no more.
